nation3/agreements-app

.github/workflows/foundry.yml
.solhint.json
foundry.toml

Configure Forge to use Solidity 0.8.13 instead of 0.8.10

chore: set solidity version

---

.github/workflows/foundry.yml
.github/workflows/yarn.yml

https://app.dework.xyz/nation3/develop-1?taskId=a7b93959-1a40-4df2-be1d-d747ef301712

chore: add macos to ci

---

.gitignore
README.md
package.json
script/CollateralAgreementDeployer.s.sol

Task details: https://app.dework.xyz/nation3/nation3-court-v1-p?taskId=85c1f9c7-95f9-4eb5-878f-0f0db169b3fb

Implement deploy script for contracts stack

---

src/agreements/CollateralAgreement.sol
src/interfaces/IAgreementFramework.sol

Original task: https://app.dework.xyz/nation3/court?taskId=a0740531-1e6e-411b-a530-1c86c3573c3d

Add metadata URI to agreement created event

---

.prettierrc.js
.solhint.json
foundry.toml
script/CollateralAgreementDeployer.s.sol
src/agreements/CollateralAgreement.sol
src/interfaces/IAgreementFramework.sol
src/interfaces/IArbitrable.sol
src/lib/AgreementStructs.sol
src/lib/CriteriaResolution.sol
src/lib/Permit.sol
test/foundry/CollateralAgreement.t.sol
test/foundry/utils/AgreementFrameworkTestBase.sol

https://app.dework.xyz/nation3/develop-1?taskId=5c7b4f2b-b72b-46d5-818d-a5d2d10fcda2
https://blog.soliditylang.org/2022/06/15/solidity-0.8.15-release-announcement/
close #33

chore: upgrade to solidity 0.8.15

---

.github/codecov.yml
.github/workflows/foundry.yml
.gitignore
README.md

https://app.dework.xyz/nation3/develop-1?taskId=f67456db-3e0b-4d07-a699-e971294c0ecb
```
forge coverage
[⠒] Compiling...
[⠆] Compiling 21 files with 0.8.13
[⠒] Solc 0.8.13 finished in 7.30s
Compiler run successful
Analysing contracts...
Running tests...
+---------------------------------------------------+-----------------+-----------------+----------------+-----------------+
| File                                              | % Lines         | % Statements    | % Branches     | % Funcs         |
+==========================================================================================================================+
| script/CollateralAgreementDeployer.s.sol          | 0.00% (0/5)     | 0.00% (0/7)     | 100.00% (0/0)  | 0.00% (0/1)     | …
```

test: enable code coverage

---

packages/contracts/Makefile
packages/contracts/README.md

adds a `Makefile` for simpler building and running initial tests

add Makefile

---

packages/contracts/remappings.txt
packages/contracts/src/Arbitrator.sol
packages/contracts/src/interfaces/IArbitrator.sol
packages/contracts/src/lib/FeeCollector.sol
packages/contracts/src/lib/ResolutionStructs.sol
packages/contracts/src/lib/Toggleable.sol
packages/contracts/src/lib/auth/Controlled.sol
packages/contracts/src/lib/auth/Owned.sol
packages/contracts/test/Arbitrator.t.sol
packages/contracts/test/CollateralAgreement.t.sol
packages/contracts/test/Controlled.t.sol
packages/contracts/test/FeeCollector.t.sol
packages/contracts/test/Owned.t.sol
packages/contracts/test/Toggleable.t.sol
packages/contracts/test/foundry/Arbitrator.t.sol
packages/contracts/test/utils/AgreementFrameworkTestBase.sol
packages/contracts/test/utils/mocks/MockArbitrable.sol
packages/contracts/test/utils/mocks/MockControlled.sol
packages/contracts/test/utils/mocks/MockFeeCollector.sol
packages/contracts/test/utils/mocks/MockOwned.sol
packages/contracts/test/utils/mocks/MockToggleable.sol

https://app.dework.xyz/nation3/court/view/board-l59hhouy?taskId=18626162-305b-4c88-ae8f-babbb0c0f5cb
Forge tests included

Implement Arbitrator

---

packages/contracts/src/Arbitrator.sol
packages/contracts/src/agreements/CollateralAgreement.sol
packages/contracts/src/lib/FeeCollector.sol
packages/contracts/test/CollateralAgreement.t.sol
packages/contracts/test/FeeCollector.t.sol

https://app.dework.xyz/nation3/court?taskId=402db61a-d0ea-496a-80e8-b9ab4ba64708
Solidity tests have been updated

Implement dispute fees

---

packages/contracts/script/CollateralAgreementDeployer.s.sol
packages/contracts/src/Arbitrator.sol
packages/contracts/src/agreements/CollateralAgreement.sol
packages/contracts/src/interfaces/IAgreementFramework.sol
packages/contracts/src/lib/AgreementStructs.sol
packages/contracts/test/CollateralAgreement.t.sol

Following changes to collateral agreements:
- Remove construction args
- Add dispute agreement with permit
- Prevent admin withdrawals of locked tokens
- Add Joined position status

Collateral agreement improvements

---

.github/workflows/web-app-ci.yml
packages/web-app/.gitignore
packages/web-app/cypress.config.ts
packages/web-app/cypress/e2e/agreements/index.cy.ts
packages/web-app/package.json
packages/web-app/pages/agreements/index.tsx
yarn.lock

Add smoke test
https://app.dework.xyz/nation3/develop-1?taskId=af2f000a-6687-46cd-a823-2571dabb0d18

chore: add integration testing

---

packages/web-app/components/agreement/actions/Joinable.tsx
packages/web-app/hooks/useAgreement.tsx

- fix(app): User balance & allowance equal to required is enough
- fix(app): Watch for updates on user's balance or allowance

Fix balance checks and watch for updates

---

packages/web-app/components/ParticipantRow.tsx
packages/web-app/components/create/context/AgreementCreationProvider.tsx
packages/web-app/components/create/context/types.tsx
packages/web-app/utils/criteria.tsx
packages/web-app/utils/metadata.tsx

https://app.dework.xyz/nation3/nation3-court-v1-p?taskId=8164be8b-ad38-4ba7-866b-577c20dea160
Closes #62 
Manually in local compilation

fix(app): Input positions balances allways BigNumber

---

packages/subgraph/abis/Arbitrator.json
packages/subgraph/networks.json
packages/subgraph/schema.graphql
packages/subgraph/src/arbitrator.ts
packages/subgraph/subgraph.yaml
packages/subgraph/tests/arbitrator-utils.ts
packages/subgraph/tests/arbitrator.test.ts

[Dework task - https://app.dework.xyz/nation3/court?taskId=65aceebe-8641-4096-a133-8f9648e7d9c4](https://app.dework.xyz/nation3/court?taskId=65aceebe-8641-4096-a133-8f9648e7d9c4)
---------------------------------------------------------------------------------------
This PR is for the subgraph to index and query disputes.

Handle Disputes in Subgraph

---

packages/ui-components/src/components/buttons/IconButton.tsx
packages/web-app/components/ParticipantRow.tsx
packages/web-app/components/create/AgreementCreationForm.tsx
packages/web-app/package.json

(https://app.dework.xyz/nation3/nation3-court-v1-p?taskId=48d1ef51-e78b-4041-af9f-5397c7a63bd8)
manually

Abuusama/dw 807/add remove participants

---

packages/ui-components/.storybook/main.js
packages/ui-components/.storybook/preview.js
packages/ui-components/package.json
packages/ui-components/src/components/steps/Steps.tsx
packages/ui-components/src/components/steps/index.tsx
packages/ui-components/stories/Steps.stories.jsx
packages/ui-components/tailwind.config.js
yarn.lock

As a bonus, Storybook now supports dark mode:

Steps component

---

packages/web-app/components/dispute/ResolutionDetails.tsx

Resolution countdown

---

packages/web-app/components/CountDown.tsx
packages/web-app/components/dispute/DisputeActions.tsx
packages/web-app/components/dispute/DisputeDetails.tsx
packages/web-app/components/dispute/ResolutionDetails.tsx
packages/web-app/components/dispute/ResolutionForm.tsx
packages/web-app/components/dispute/context/DisputeResolutionContext.tsx
packages/web-app/components/dispute/context/DisputeResolutionProvider.tsx
packages/web-app/hooks/useArbitrator.tsx
packages/web-app/hooks/useCohort.tsx
packages/web-app/hooks/useTime.tsx
packages/web-app/lib/constants.tsx
packages/web-app/package.json
packages/web-app/tailwind.config.js
yarn.lock

Integrate Safe SDK to fetch, propose, approve & reject resolution proposals from the judges Cohort Safe.
Still need some polishing but provides the basic functionality.

Integrate Safe actions in the disputes UI

---

packages/web-app/components/dispute/DisputeActions.tsx
packages/web-app/components/dispute/ResolutionDetails.tsx
packages/web-app/pages/agreement/[id].tsx

Tweak resolution details & appeal modal to be more consistent with the new modals.

Appeal tweaks

---

packages/web-app/components/agreement/actions/Joinable.tsx

fix: Bignumber eval

---

packages/web-app/lib/constants.tsx

Appeal cost is 1 NATION, not 10.

fix: Incorrect mainnet appeal cost

---

packages/ui-components/src/components/Organisms/modals/ModalNew.tsx
packages/web-app/components/JoinModal.tsx
packages/web-app/components/MarkdownFile/MarkdownFile.tsx
packages/web-app/components/agreement/AgreementCard/AgreementCard.tsx

- Fix: Not being able to review private or restricted terms on the review step on the creation process
- Fix: Modals closing when clicking anywhere
- Fix: Ledger gas-less approvals warning breaking layout
- Fix: Gas-less approvals toggle not updating correctly

Release fixes

---

packages/web-app/.env.sample

https://thegraph.com/hosted-service/subgraph/nation3/nation3-agreements-sepolia
https://thegraph.com/hosted-service/subgraph/nation3/nation3-agreements-mainnet

chore: update env

---

README.md

Add Sepolia URL
